name: Split repository
on: [push]

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: ./run split
